/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.awt.event.ActionListener;
import java.awt.event.ItemListener;
import javax.swing.JComboBox;
import java.util.Enumeration;
import javax.swing.AbstractButton;
import javax.swing.JRadioButton;

/**
 * interfaz para Modificar un Tour
 * @author Equipo #4
 */
public class IModificarTour extends javax.swing.JFrame {

    /**
     * Creates new form IModificarTour
     */
    public IModificarTour() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GrupoDisponibilidad = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        tour_seleccionado = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        nuevo_nombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        radio_disponible = new javax.swing.JRadioButton();
        radio_noDisponible = new javax.swing.JRadioButton();
        boton_atras = new javax.swing.JButton();
        boton_modificar = new javax.swing.JButton();
        nuevo_id = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Comité de Obras de Arte");

        jLabel1.setText("Modificar Tour:");

        jLabel2.setText("Nuevo Nombre:");

        jLabel3.setText("Disponibilidad:");

        GrupoDisponibilidad.add(radio_disponible);
        radio_disponible.setText("Disponible");

        GrupoDisponibilidad.add(radio_noDisponible);
        radio_noDisponible.setText("No Disponible");

        boton_atras.setText("Atras");

        boton_modificar.setText("Modificar");

        nuevo_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevo_idActionPerformed(evt);
            }
        });

        jLabel4.setText("Nuevo ID:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radio_disponible)
                            .addComponent(radio_noDisponible)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tour_seleccionado, 0, 406, Short.MAX_VALUE)
                            .addComponent(nuevo_nombre)
                            .addComponent(nuevo_id, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel4))
                .addContainerGap(81, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(boton_atras)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 402, Short.MAX_VALUE)
                .addComponent(boton_modificar)
                .addGap(61, 61, 61))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tour_seleccionado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nuevo_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nuevo_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(radio_disponible)
                        .addGap(3, 3, 3)
                        .addComponent(radio_noDisponible))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boton_atras)
                    .addComponent(boton_modificar))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nuevo_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevo_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nuevo_idActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IModificarTour.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IModificarTour.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IModificarTour.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IModificarTour.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IModificarTour().setVisible(true);
            }
        });
    }
    
    /**
     * Agrega escuchador del evento de presionar el boton
     * @param listenForBotonAtras
     */
    public void addBotonAtrasListener(ActionListener listenForBotonAtras) {
        boton_atras.addActionListener(listenForBotonAtras);
    }

    /**
     * Agrega escuchador del evento de presionar el boton
     * @param listenForBotonModificar
     */
    public void addBotonModificarListener(ActionListener listenForBotonModificar) {
        boton_modificar.addActionListener(listenForBotonModificar);
    }
    
    /**
     * Agrega escuchador del evento de seleccionar un item del combo box
     * @param listenForComboBox
     */
    public void addComboBoxListener(ItemListener listenForComboBox) {
        tour_seleccionado.addItemListener(listenForComboBox);
    }
    
    /**
     * Retorna el combo box del tour seleccionado a modificar
     * @return el combo box del tour seleccionado a modificar
     */
    public JComboBox<String> getComboBox() {
        return tour_seleccionado;
    }
    
    /**
     * Retorna el nombre del tour a modificar
     * @return nombre de tour a modificar
     */
    public String tourSeleccionado(){
        if (tour_seleccionado.getSelectedItem() != null) {
            String x = tour_seleccionado.getSelectedItem().toString();
            return x;
        }
        return "";
    }
    
    /**
     * Retorna radio button de disponible
     * @return radio button de disponible
     */
    public JRadioButton getRadioDisponible() {
        return radio_disponible;
    }
    
    /**
     * Retorna radio button de no disponible
     * @return redio button de no disponible
     */
    public JRadioButton getRadioNoDisponible() {
        return radio_noDisponible;
    }
    
    /**
     * Retorna nombre nuevo del tour a modificar
     * @return nombre nuevo del tour a modificar
     */
    public String nuevoNombre () {
        String nuevoNombre;
        nuevoNombre = nuevo_nombre.getText();
        return nuevoNombre;
    }
    
    /**
     * Retorna ID nuevo del tour a modificar
     * @return ID nuevo del tour a modificar
     */
    public int nuevoID () {
        int nombreID;
        String text;
        text=nuevo_id.getText();
        if ("".equals(text)) {
            return -1000;
        }else{
            nombreID=Integer.parseInt(text);
            return nombreID;
        }
    }
    
    /**
     * Retorna valor del radio buton seleccionado
     * @return valor del radio buton seleccionado
     */
    public boolean getSelectedButton()
    {  
        for (Enumeration<AbstractButton> buttons = GrupoDisponibilidad.getElements(); buttons.hasMoreElements();) {
                AbstractButton button = buttons.nextElement();
                if (button.isSelected()) {
                    if("Disponible".equals(button.getText())){
                        return true;
                    }
                    if("No Disponible".equals(button.getText())){
                        return false;
                    }                 
                }
            }
        return false;
    }
    
    /**
     * Limpia la interfaz de los datos anteriores
     */
    public void limpiar () {
        nuevo_nombre.setText("");
        nuevo_id.setText("");
        GrupoDisponibilidad.clearSelection();
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup GrupoDisponibilidad;
    private javax.swing.JButton boton_atras;
    private javax.swing.JButton boton_modificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField nuevo_id;
    private javax.swing.JTextField nuevo_nombre;
    private javax.swing.JRadioButton radio_disponible;
    private javax.swing.JRadioButton radio_noDisponible;
    private javax.swing.JComboBox<String> tour_seleccionado;
    // End of variables declaration//GEN-END:variables
}
